apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImMyRm1aWEp1WVc1a1pYbzJOalk2UVhKblpXNTBhVzVoTVRrNE1Db2xQejg9IgoJCX0KCX0sCgkiSHR0cEhlYWRlcnMiOiB7CgkJIlVzZXItQWdlbnQiOiAiRG9ja2VyLUNsaWVudC8xOS4wMy44IChsaW51eCkiCgl9Cn0=
kind: Secret
metadata:
  name: docker-auth
  namespace: cicd
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: git-auth
  namespace: cicd
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: sfernandez666
  password: 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