apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: cicd
  name: dockerhub-service
secrets:
  - name: docker-auth # Credenciales de Docker Hub
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: cicd
  name: github-service
secrets:
  - name: git-auth