apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  namespace: cicd
  name: build-push
spec:
  serviceAccountName: dockerhub-service
  taskRef:
    name: build-push
  params:
    - name: pathToDockerFile
      value: Dockerfile
  resources:
    inputs:
      - name: docker-source
        resourceRef:
          name: devops-git
    outputs:
      - name: builtImage
        resourceRef:
          name: devops-image