apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  namespace: cicd
  name: build-docker-image-from-git-source-task-run
spec:
  serviceAccountName: dockerhub-service
  taskRef:
    name: build-docker-image-from-git-source
  params:
    - name: pathToDockerFile
      value: Dockerfile
  resources:
    inputs:
      - name: docker-source
        resourceRef:
          name: devops-git
    outputs:
      - name: builtImage
        resourceRef:
          name: devops-tekton-demo-image