apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: build-helloworld-docker
spec:
  serviceAccountName: build-bot
  taskRef:
    name: build-docker-image-from-git-source
  params:
    - name: pathToDockerFile
      value: Dockerfile
    - name: pathToContext
      value: $(resources.inputs.docker-source.path)/app
  resources:
    inputs:
      - name: docker-source
        resourceRef:
          name: git-knative-tutorial
    outputs:
      - name: builtImage
        resourceRef:
          name: image-docker-knative-tutorial