apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: devops-git
spec:
  type: git
  params:
    - name: revision
      value: main
    - name: url
      value: https://github.com/safernandez666/devops

---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: devops-tekton-demo-image
spec:
  type: image
  params:
    - name: url
      value: safernandez666/app